services:
  - type: web
    name: python-agent
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
